import { defineConfig } from "vitest/config";
export default defineConfig({
  test: {
    include: [
      "tests/project-hub.test.ts",
      "tests/clean-capture.test.ts",
      "tests/app-analytics.test.ts",
      "tests/weapon-stat-marks.test.ts",
      "tests/room-invite.test.ts",
      "tests/coop-performance.test.ts",
      "tests/adaptive-quality.test.ts",
      "tests/frame-pacer.test.ts",
      "tests/state-wire.test.ts",
      "tests/room-directory.test.ts",
      "tests/shared-armory.test.ts",
      "tests/social.test.ts",
      "tests/training.test.ts",
      "tests/developer-auth.test.ts",
      "tests/encounter-camera.test.ts",
      "tests/audio.test.ts",
      "tests/enemy-size.test.ts",
      "tests/foundry-generation.test.ts",
      "tests/foundry-movement.test.ts",
      "tests/aim.test.ts",
      "tests/standard-trooper.test.ts",
      "tests/hound-motion.test.ts",
      "tests/structure-motion.test.ts",
      "tests/enemy-report-motion.test.ts",
      "tests/maps.test.ts",
      "tests/terrain.test.ts",
      "tests/scenery-boundary.test.ts",
      "tests/structure-v2.test.ts",
      "tests/enemies.test.ts",
      "tests/stages.test.ts",
      "tests/armory.test.ts",
      "tests/game.test.ts",
      "tests/p1.test.ts",
      "tests/layout.test.ts",
      "tests/render.test.ts",
      "tests/rescue.test.ts",
      "tests/hornet.test.ts",
    ],
    testTimeout: 30000,
    // Full mission simulations compete for CPU and can exhaust the wall-clock timeout.
    fileParallelism: false,
  },
});
