export const adminPage = String.raw`<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><title>アプリ管理</title>
<style>
:root{color-scheme:dark;font-family:system-ui,-apple-system,sans-serif;background:#0c1820;color:#e8f1f2}*{box-sizing:border-box}body{max-width:720px;margin:auto;padding:24px 16px calc(24px + env(safe-area-inset-bottom))}h1{font-size:26px;margin:0}h2{font-size:20px;margin:0}p{line-height:1.65}.muted,small{color:#a8c0cb}button,input,select{font:inherit;min-height:44px;border-radius:10px;border:1px solid #466373;background:#17303a;color:inherit;padding:10px 13px}button{cursor:pointer}button:disabled{opacity:.55;cursor:wait}button:focus-visible,a:focus-visible,select:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #70ead1;outline-offset:3px}a{color:#81ead6;text-underline-offset:4px}header,.tools,.card-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.tools{flex-wrap:wrap;margin:22px 0 10px}.tools label{display:flex;align-items:center;gap:8px}.card{background:#17303a;border:1px solid #2e4b59;border-radius:16px;padding:18px;margin:14px 0}.tag{white-space:nowrap;font-size:12px;border:1px solid #4c6a74;border-radius:30px;padding:5px 9px;color:#b5d6da}.tag.ok{color:#89efca;border-color:#447f71}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}.metric strong{font-size:30px;display:block;line-height:1.3;font-variant-numeric:tabular-nums}.metric span{font-size:13px;color:#b6ccd5}.spark{display:flex;align-items:flex-end;gap:3px;height:55px;margin:16px 0 4px}.spark i{display:block;flex:1;background:#53c7b0;border-radius:3px 3px 0 0;min-width:0}.dates{display:flex;justify-content:space-between;font-size:12px;color:#a8c0cb}.detail-row{display:flex;justify-content:space-between;gap:10px;padding:8px 0;border-bottom:1px solid #31505c;font-size:14px}summary{cursor:pointer;padding:13px 0;min-height:44px}details p{font-size:14px}#msg{color:#ffd397;min-height:1.5em}#login{margin-top:32px}#login label{display:block;margin-bottom:8px}#pw{width:100%;margin:0 0 12px}#login button{width:100%;background:#276757}.note{font-size:13px}.empty{padding:10px 0;color:#bdd0d8}.card-foot{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;margin-top:14px}.card-foot a{padding:8px 0;font-size:14px}.card-foot small{font-size:12px}#updated{font-size:13px}#cards[aria-busy=true]{opacity:.65}@media(max-width:360px){body{padding:18px 12px}.card{padding:14px}.card-head{gap:6px}h2{font-size:18px}.metric strong{font-size:27px}}
</style></head><body><header><div><p class="muted" style="margin:0 0 6px;font-size:12px;letter-spacing:.12em">MY APPS</p><h1>アプリ管理</h1></div><button id="out" hidden>ログアウト</button></header>
<form id="login"><label for="pw">開発者パスワード</label><input id="pw" type="password" autocomplete="current-password" required><button id="go" type="submit">ログイン</button></form><p id="msg" role="status" aria-live="polite"></p>
<section id="app" hidden><div class="tools"><label for="period">期間 <select id="period"><option value="1">今日</option><option value="7" selected>7日間</option><option value="30">30日間</option></select></label><button id="refresh">更新</button></div><p id="updated" class="muted"></p><main id="cards" aria-label="アプリ別アクセス状況"></main><p class="note muted">日本時間で集計。アクセスはページ表示回数です。訪問ブラウザは各アプリ内・日別に重複を除いた数で、人数ではありません。複数日の値は日別の延べ数です。計測を拒否した端末や通信失敗は含まれない場合があります。</p></section>
<script>
(()=>{'use strict';const $=id=>document.getElementById(id),num=n=>new Intl.NumberFormat('ja-JP').format(n);let generation=0,loading=false;
const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el};
async function api(url,options){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000),...options});const d=await r.json();return[r,d]}
function signedOut(){generation++;$('cards').replaceChildren();$('app').hidden=true;$('out').hidden=true;$('login').hidden=false;$('pw').value=''}
function metric(label,value){const d=node('div',undefined,'metric');d.append(node('span',label),node('strong',num(value)));return d}
function card(a,period){const c=node('article',undefined,'card'),head=node('div',undefined,'card-head');head.append(node('h2',a.name),node('span',a.status==='active'?'計測中':a.status==='error'?'取得失敗':a.status==='unconfigured'?'未連携':'計測待ち','tag'+(a.status==='active'?' ok':'')));c.append(head);
 if(a.status==='active'){const m=node('div',undefined,'metrics');m.append(metric('アクセス',a.totals.views),metric(period===1?'訪問ブラウザ':'延べ訪問ブラウザ',a.totals.visitors));c.append(m);c.append(node('small','今日 '+num(a.todayViews)+' / 昨日 '+num(a.yesterdayViews)+'　前日比 '+(a.change===null?'—':(a.change>0?'+':'')+a.change+'%')));
 const chart=node('div',undefined,'spark');chart.setAttribute('role','img');chart.setAttribute('aria-label',period+'日間のアクセス推移。数値は詳細で確認できます');const max=Math.max(1,...a.days.map(d=>d.views));a.days.forEach(d=>{const bar=node('i');bar.style.height=(d.views?Math.max(3,d.views/max*100):0)+'%';bar.title=d.date+'：'+num(d.views);chart.append(bar)});const dates=node('div',undefined,'dates');dates.append(node('span',a.days[0].date.slice(5)),node('span',a.days.at(-1).date.slice(5)));c.append(chart,dates);
 const details=node('details');details.append(node('summary','日別の数値を見る'));if(a.id==='swarm-front')details.append(node('p','この期間の出撃 '+num(a.totals.sorties)+' / クリア '+num(a.totals.clears)));a.days.slice().reverse().forEach(d=>{const row=node('div',undefined,'detail-row');row.append(node('span',d.date),node('span',num(d.views)+' 回 / '+num(d.visitors)+' ブラウザ'));details.append(row)});c.append(details);
 }else c.append(node('p',a.status==='error'?'データを取得できませんでした。更新して再試行してください。':a.status==='unconfigured'?'接続先を確認中です。':'まだ計測データがありません。連携後のアクセスから表示します。','empty'));
 const foot=node('div',undefined,'card-foot');if(a.url){const link=node('a','アプリを開く ↗');link.href=a.url;link.target='_blank';link.rel='noopener noreferrer';foot.append(link)}if(a.firstDate)foot.append(node('small','記録あり：'+a.firstDate+'〜'));c.append(foot);return c}
async function load(){const id=++generation;loading=true;$('refresh').disabled=true;$('cards').setAttribute('aria-busy','true');$('msg').textContent='';try{const period=Number($('period').value);const[r,d]=await api('/api/developer/apps?days='+period);if(id!==generation)return;if(r.status===401){signedOut();$('msg').textContent='ログインしてください';return}if(!r.ok)throw Error();$('login').hidden=true;$('out').hidden=false;$('app').hidden=false;$('cards').replaceChildren(...d.apps.map(a=>card(a,period)));$('updated').textContent='取得：'+new Date(d.updatedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})+'（日本時間）';}catch{if(id===generation){$('cards').replaceChildren();$('updated').textContent='';$('msg').textContent='取得に失敗しました。通信を確認して再試行してください。'}}finally{if(id===generation){loading=false;$('refresh').disabled=false;$('cards').setAttribute('aria-busy','false')}}}
$('login').addEventListener('submit',async e=>{e.preventDefault();$('go').disabled=true;$('msg').textContent='';try{const[r,d]=await api('/api/developer/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('pw').value})});$('pw').value='';if(!r.ok){$('msg').textContent=d.error||'ログインに失敗しました';return}await load()}catch{$('msg').textContent='通信に失敗しました。再試行してください。'}finally{$('go').disabled=false}});
$('out').onclick=async()=>{$('out').disabled=true;try{const[r]=await api('/api/developer/logout',{method:'POST'});if(!r.ok)throw Error();signedOut();$('msg').textContent='ログアウトしました'}catch{$('msg').textContent='ログアウトに失敗しました。再試行してください。'}finally{$('out').disabled=false}};
$('period').onchange=load;$('refresh').onclick=load;load();})();
</script></body></html>`;
